---
output:
  pdf_document: default
  html_document: default
---
#Projet statistique :

##Charger les données :
###Installer les packages nécessaires :
```{r}
install.packages("xlsx")

```
###Charger les données :
```{r}
# xlsx files
library(xlsx)
my_data <- read.xlsx("dataset.xlsx",sheetIndex = 1,as.data.frame = T,encoding = 'UTF-8')

```
### nommer les colonnes :
```{r}
my_col_names=c('date','a_suivi','performer_travail_projet_1','motivation_certificat_1','trouver_emploi_1','mooc_inclu_etude_1','edt_chargee_1','plateformes_connues','aide_financiere_1','prix_1','outils_exercices_1','sciences_donnees_1','informatique_1','sciences_physiques_1','business_1','arts_1','langues_1','sciences_sociales_1','performer_travail_projet','motivation_certificat','trouver_emploi','nbr_certificat','satisfait_gestion_temps','objectifs_atteints','satisfaction','vacances_etude','temps_alloue_cours','mooc_inclu_etude','edt_chargee','plateformes_utilisees','videos_cours','transcription','diapositives_cours','forum_discussion','examens_exercices','accompagnement_pedagogique','aides_financiere','prix','outils_exercice','sciences_donnees','informatique','sciences_physiques','business','arts','langues','sciences_sociales','sexe','pays','age','est_etudiant','niveau_actuel','formation','background','mail','commentaire')
colnames(my_data)<-my_col_names
```
### Choisir lignes intérressants :
```{r}
my_data2<-my_data[c(3:nrow(my_data)),]

```

###Eliminer les colonnes : mail, date 
```{r}
my_data2$date<-NULL
my_data2$mail<-NULL
my_data2$commentaire<-NULL
```
### créer les  dataframes nécessaires: 
#### librairie pour filtrer les lignes :
```{r}
library("dplyr")
```

#### jamais suivi :
```{r}
data_jamais<-filter(my_data2,a_suivi=="Jamais")
# supprimer les colonnes avec que de Nans :
data_jamais<-data_jamais[ , ! apply( data_jamais , 2 , function(x) all(is.na(x)) ) ]
# Write CSV in R
write.csv(data_jamais, file = "data_jamais.csv")
```


#### suivi terminé et pas terminé :
```{r}
data_suivi<-filter(my_data2,a_suivi  %in% c("Oui, je l'ai suivi mais je ne l'ai pas terminé", "Oui, je l'ai suivi et j'ai réussi" ))
data_suivi<-data_suivi[ , ! apply( data_suivi , 2 , function(x) all(is.na(x)) ) ]
write.csv(data_suivi, file = "data_suivi.csv")

```

####suivi mais pas terminé :
```{r}
data_non_termine<-filter(my_data2,a_suivi  %in% c("Oui, je l'ai suivi mais je ne l'ai pas terminé"))
data_non_termine<-data_non_termine[ , ! apply( data_non_termine , 2 , function(x) all(is.na(x)) ) ]
write.csv(data_non_termine, file = "data_non_termine.csv")

```

####suivi et terminé :
```{r}
data_termine<-filter(my_data2,a_suivi  %in% c( "Oui, je l'ai suivi et j'ai réussi" ))
data_termine<-data_termine[ , ! apply( data_termine , 2 , function(x) all(is.na(x)) ) ]
write.csv(data_termine, file = "data_termine.csv")

```

